server:
  port: 8080

spring:
  profiles:
    active: qa

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: springbootpractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P9th7@1224
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Hello world


management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: qa
  application:
    name: springbootpractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P9th7@1224
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Hello QA

management:
  endpoints:
    web:
      exposure:
        include: "*"


---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: springbootpractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P9th7@1224
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

welcome:
  message: Hello Prod