server:
  port: 8080
spring:
  application:
    name: springbootpractice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P9th7@1224
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

welcome:
  message: Hello world